<a href="https://colab.research.google.com/github/kusa-mochi/pracitce-data-science/blob/master/PracticeNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

In [21]:
%precision 3

'%.3f'

In [22]:
data = np.array([9,2,3,4,10,6,7,8,1,5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [23]:
data.dtype

dtype('int64')

In [24]:
print('次元数：', data.ndim)
print('要素数：', data.size)

次元数： 1
要素数： 10


In [25]:
data * 2

array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])

In [26]:
np.array([1,2,3]) * np.array([10,9,8])

array([10, 18, 24])

In [27]:
np.array([1,2,3]) ** 2

array([1, 4, 9])

In [28]:
np.array([1,2,3]) / np.array([10,9,8])

array([0.1  , 0.222, 0.375])